#!/usr/bin/env bash
# while loop with if, elif, and else statements
a=1
while [ $a -lt 11 ]
do
	if [ $a -eq 4 ]
	then
		echo "bad luck"
	elif [ $a -eq 8 ]
	then
		echo "good luck"
	else
		echo "Best School"
	fi
	((a++))
done
