#!/usr/bin/env bash
# nested loop to print  hours an minutes
hour=0
while [ $hour -le 12 ]
do
	echo "Hour: $hour"
	minutes=1
	while [ $minutes -le 59 ]
	do
		echo "$minutes"
		((minutes++))
	done
	((hour++))
done
